apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caresync.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "caresync.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
  JWT_EXPIRES_IN: {{ .Values.backend.env.JWT_EXPIRES_IN | quote }}
  JWT_REFRESH_EXPIRES_IN: {{ .Values.backend.env.JWT_REFRESH_EXPIRES_IN | quote }}
  FRONTEND_URL: {{ .Values.configMap.frontendUrl | quote }}
  DATABASE_HOST: {{ include "caresync.databaseHost" . | quote }}
  DATABASE_PORT: {{ include "caresync.databasePort" . | quote }}
  DATABASE_NAME: {{ include "caresync.databaseName" . | quote }}
