{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "caresync.fullname" . }}-backend-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "caresync.backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "caresync.backend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "caresync.frontend.selectorLabels" . | nindent 14 }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "caresync.fullname" . }}-frontend-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "caresync.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "caresync.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "caresync.backend.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
{{- end }}
