apiVersion: v1
kind: ConfigMap
metadata:
  name: caresync-config
  namespace: ian-malavi-mhambe
  labels:
    app.kubernetes.io/name: caresync
data:
  NODE_ENV: "production"
  PORT: "5000"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  FRONTEND_URL: "https://ian-malavi-mhambe.capstone.tiberbu.com"
