apiVersion: v1
kind: Namespace
metadata:
  name: ian-malavi-mhambe
  labels:
    app.kubernetes.io/name: caresync
    app.kubernetes.io/part-of: caresync-platform
    project: caresync
    owner: ian-malavi-mhambe
